version: '3' 
services:
  api:
    container_name: fib_server
    build: 
      context: ./api/.
      dockerfile: Dockerfile.dev
    volumes:
      - ./api:/api
    ports:
      - 8888:8888
    tty: true